# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Interface_module.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCharts import QChartView
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QGraphicsView, QHeaderView,
    QLabel, QLineEdit, QProgressBar, QPushButton,
    QSizePolicy, QStackedWidget, QTableView, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1044, 871)
        self.Testing_interface_button = QPushButton(Form)
        self.Testing_interface_button.setObjectName(u"Testing_interface_button")
        self.Testing_interface_button.setGeometry(QRect(290, 20, 211, 41))
        font = QFont()
        font.setPointSize(18)
        self.Testing_interface_button.setFont(font)
        self.stackedWidget = QStackedWidget(Form)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(0, 80, 1041, 781))
        self.Main_interface = QWidget()
        self.Main_interface.setObjectName(u"Main_interface")
        self.Tool_information_enty = QPushButton(self.Main_interface)
        self.Tool_information_enty.setObjectName(u"Tool_information_enty")
        self.Tool_information_enty.setGeometry(QRect(150, 160, 141, 31))
        font1 = QFont()
        font1.setPointSize(14)
        self.Tool_information_enty.setFont(font1)
        self.Tool_category_comboBox = QComboBox(self.Main_interface)
        self.Tool_category_comboBox.addItem("")
        self.Tool_category_comboBox.addItem("")
        self.Tool_category_comboBox.addItem("")
        self.Tool_category_comboBox.addItem("")
        self.Tool_category_comboBox.setObjectName(u"Tool_category_comboBox")
        self.Tool_category_comboBox.setGeometry(QRect(120, 100, 161, 31))
        self.Tool_category_comboBox.setFont(font1)
        self.label_4_1_2 = QLabel(self.Main_interface)
        self.label_4_1_2.setObjectName(u"label_4_1_2")
        self.label_4_1_2.setGeometry(QRect(20, 100, 91, 31))
        self.label_4_1_2.setFont(font1)
        self.Input_tool_information = QLineEdit(self.Main_interface)
        self.Input_tool_information.setObjectName(u"Input_tool_information")
        self.Input_tool_information.setGeometry(QRect(450, 99, 571, 31))
        self.Tool_information_view = QTableView(self.Main_interface)
        self.Tool_information_view.setObjectName(u"Tool_information_view")
        self.Tool_information_view.setGeometry(QRect(275, 200, 761, 541))
        self.Tool_information_search_button = QPushButton(self.Main_interface)
        self.Tool_information_search_button.setObjectName(u"Tool_information_search_button")
        self.Tool_information_search_button.setGeometry(QRect(310, 100, 131, 31))
        self.Tool_information_search_button.setFont(font1)
        self.Tool_information_delete = QPushButton(self.Main_interface)
        self.Tool_information_delete.setObjectName(u"Tool_information_delete")
        self.Tool_information_delete.setGeometry(QRect(320, 160, 131, 31))
        self.Tool_information_delete.setFont(font1)
        self.label_4_1_1 = QLabel(self.Main_interface)
        self.label_4_1_1.setObjectName(u"label_4_1_1")
        self.label_4_1_1.setGeometry(QRect(370, 20, 201, 41))
        self.label_4_1_1.setFont(font)
        self.Tool_image_view = QGraphicsView(self.Main_interface)
        self.Tool_image_view.setObjectName(u"Tool_image_view")
        self.Tool_image_view.setGeometry(QRect(10, 200, 256, 192))
        self.Tool_data_view = QTableView(self.Main_interface)
        self.Tool_data_view.setObjectName(u"Tool_data_view")
        self.Tool_data_view.setGeometry(QRect(10, 400, 256, 341))
        self.stackedWidget.addWidget(self.Main_interface)
        self.Visual_interface = QWidget()
        self.Visual_interface.setObjectName(u"Visual_interface")
        self.Chart_drill = QChartView(self.Visual_interface)
        self.Chart_drill.setObjectName(u"Chart_drill")
        self.Chart_drill.setGeometry(QRect(10, 60, 300, 300))
        self.Chart_indexmill = QChartView(self.Visual_interface)
        self.Chart_indexmill.setObjectName(u"Chart_indexmill")
        self.Chart_indexmill.setGeometry(QRect(370, 60, 300, 300))
        self.chart_solidmill = QChartView(self.Visual_interface)
        self.chart_solidmill.setObjectName(u"chart_solidmill")
        self.chart_solidmill.setGeometry(QRect(10, 460, 300, 300))
        self.Chart_turninsert = QChartView(self.Visual_interface)
        self.Chart_turninsert.setObjectName(u"Chart_turninsert")
        self.Chart_turninsert.setGeometry(QRect(360, 460, 300, 300))
        self.label = QLabel(self.Visual_interface)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(100, 10, 111, 41))
        self.label.setFont(font1)
        self.label_3 = QLabel(self.Visual_interface)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(440, 10, 131, 41))
        self.label_3.setFont(font1)
        self.label_4 = QLabel(self.Visual_interface)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(80, 410, 121, 41))
        self.label_4.setFont(font1)
        self.label_5 = QLabel(self.Visual_interface)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(450, 410, 141, 41))
        self.label_5.setFont(font1)
        self.label_6 = QLabel(self.Visual_interface)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(740, 50, 251, 131))
        font2 = QFont()
        font2.setPointSize(20)
        self.label_6.setFont(font2)
        self.Image_refresh_button = QPushButton(self.Visual_interface)
        self.Image_refresh_button.setObjectName(u"Image_refresh_button")
        self.Image_refresh_button.setGeometry(QRect(800, 180, 131, 41))
        self.Image_refresh_button.setFont(font1)
        self.stackedWidget.addWidget(self.Visual_interface)
        self.Testing_interface = QWidget()
        self.Testing_interface.setObjectName(u"Testing_interface")
        self.Data_import_button = QPushButton(self.Testing_interface)
        self.Data_import_button.setObjectName(u"Data_import_button")
        self.Data_import_button.setGeometry(QRect(30, 110, 141, 41))
        self.Data_import_button.setFont(font1)
        self.File_path_display = QLabel(self.Testing_interface)
        self.File_path_display.setObjectName(u"File_path_display")
        self.File_path_display.setGeometry(QRect(180, 110, 461, 41))
        font3 = QFont()
        font3.setPointSize(12)
        self.File_path_display.setFont(font3)
        self.Start_data_analysis_button = QPushButton(self.Testing_interface)
        self.Start_data_analysis_button.setObjectName(u"Start_data_analysis_button")
        self.Start_data_analysis_button.setGeometry(QRect(30, 180, 141, 41))
        self.Start_data_analysis_button.setFont(font1)
        self.Data_analysis_loading_progress_bar = QProgressBar(self.Testing_interface)
        self.Data_analysis_loading_progress_bar.setObjectName(u"Data_analysis_loading_progress_bar")
        self.Data_analysis_loading_progress_bar.setGeometry(QRect(190, 190, 751, 31))
        self.Data_analysis_loading_progress_bar.setFont(font1)
        self.Data_analysis_loading_progress_bar.setValue(0)
        self.label_2 = QLabel(self.Testing_interface)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(390, 20, 201, 51))
        self.label_2.setFont(font)
        self.Data_analysis_result_presentation = QChartView(self.Testing_interface)
        self.Data_analysis_result_presentation.setObjectName(u"Data_analysis_result_presentation")
        self.Data_analysis_result_presentation.setGeometry(QRect(10, 260, 1021, 511))
        self.stackedWidget.addWidget(self.Testing_interface)
        self.Main_interface_button = QPushButton(Form)
        self.Main_interface_button.setObjectName(u"Main_interface_button")
        self.Main_interface_button.setGeometry(QRect(40, 20, 221, 41))
        self.Main_interface_button.setFont(font)
        self.Visual_interface_button = QPushButton(Form)
        self.Visual_interface_button.setObjectName(u"Visual_interface_button")
        self.Visual_interface_button.setGeometry(QRect(530, 20, 231, 41))
        self.Visual_interface_button.setFont(font)

        self.retranslateUi(Form)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.Testing_interface_button.setText(QCoreApplication.translate("Form", u"\u5200\u5177\u78e8\u635f\u68c0\u6d4b\u754c\u9762", None))
        self.Tool_information_enty.setText(QCoreApplication.translate("Form", u"\u5200\u5177\u4fe1\u606f\u5f55\u5165", None))
        self.Tool_category_comboBox.setItemText(0, QCoreApplication.translate("Form", u"\u5b54\u52a0\u5de5\u5200\u5177", None))
        self.Tool_category_comboBox.setItemText(1, QCoreApplication.translate("Form", u"\u53ef\u8f6c\u4f4d\u94e3\u5200\u5200\u5177", None))
        self.Tool_category_comboBox.setItemText(2, QCoreApplication.translate("Form", u"\u56fa\u5b9a\u94e3\u5200\u5200\u5177", None))
        self.Tool_category_comboBox.setItemText(3, QCoreApplication.translate("Form", u"\u8f66\u524a\u5200\u7247", None))

        self.label_4_1_2.setText(QCoreApplication.translate("Form", u"\u5200\u5177\u7c7b\u522b\uff1a", None))
        self.Input_tool_information.setText(QCoreApplication.translate("Form", u"\u8bf7\u8f93\u5165\u5200\u5177\u76f8\u5173\u4fe1\u606f", None))
        self.Tool_information_search_button.setText(QCoreApplication.translate("Form", u"\u5200\u5177\u4fe1\u606f\u68c0\u7d22", None))
        self.Tool_information_delete.setText(QCoreApplication.translate("Form", u"\u5200\u5177\u4fe1\u606f\u5220\u9664", None))
        self.label_4_1_1.setText(QCoreApplication.translate("Form", u"\u5200\u5177\u6570\u636e\u5e93\u4e3b\u754c\u9762", None))
        self.label.setText(QCoreApplication.translate("Form", u"\u5b54\u52a0\u5de5\u5200\u5177", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"\u53ef\u8f6c\u4f4d\u94e3\u5200\u5200\u5177", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"\u56fa\u5b9a\u94e3\u5200\u5200\u5177", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"\u8f66\u524a\u94e3\u5200\u5200\u5177", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"\u5200\u5177\u4fe1\u606f\u53ef\u89c6\u5316\u754c\u9762", None))
        self.Image_refresh_button.setText(QCoreApplication.translate("Form", u"\u56fe\u50cf\u5237\u65b0", None))
        self.Data_import_button.setText(QCoreApplication.translate("Form", u"\u76d1\u6d4b\u6570\u636e\u5bfc\u5165", None))
        self.File_path_display.setText(QCoreApplication.translate("Form", u"\u6587\u4ef6\u8def\u5f84", None))
        self.Start_data_analysis_button.setText(QCoreApplication.translate("Form", u"\u5f00\u59cb\u6570\u636e\u5206\u6790", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\u5200\u5177\u78e8\u635f\u68c0\u6d4b\u754c\u9762", None))
        self.Main_interface_button.setText(QCoreApplication.translate("Form", u"\u5200\u5177\u6570\u636e\u5e93\u4e3b\u754c\u9762", None))
        self.Visual_interface_button.setText(QCoreApplication.translate("Form", u"\u5200\u5177\u4fe1\u606f\u53ef\u89c6\u5316\u754c\u9762", None))
    # retranslateUi

